# Generated by Django 4.1.7 on 2023-02-23 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bordas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borda', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('valor_borda', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='PedidoPizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizza', models.CharField(max_length=1000)),
                ('tamanho', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sabores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sabor', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('valor_sabor', models.DecimalField(decimal_places=2, max_digits=4)),
                ('especial', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PedidoPizzaFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pizzaria.bordas')),
                ('flavor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pizzaria.sabores')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pizzaria.pedidopizza')),
            ],
        ),
        migrations.AddField(
            model_name='pedidopizza',
            name='pizza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pizzaria.pizza'),
        ),
    ]
