# Generated by Django 4.1.7 on 2023-02-22 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bordas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borda', models.CharField(max_length=200)),
                ('valor_borda', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Sabores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sabor', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('valor_sabor', models.DecimalField(decimal_places=2, max_digits=4)),
                ('especial', models.BooleanField(default=0)),
            ],
        ),
    ]
